/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rockpaperscissorsgui;

import java.awt.Toolkit;
import javax.swing.SwingConstants;
import static rockpaperscissorsgui.RockPaperScissorsGUI.rand;

/**
 *
 * @author aocar
 */
public class Game extends javax.swing.JFrame {

    static int userScore = 0;
    static int computerScore = 0;
    
    public Game() {
        initComponents();
        winMessage.setVisible(false);
        loseMessage.setVisible(false);
        drawMessage.setVisible(false);
        scissors1.setVisible(false);
        paper1.setVisible(false);
        rock1.setVisible(false);
        playAgain.setVisible(false);
        yes.setVisible(false);
        no.setVisible(false);
        variableUserScore.setText(String.valueOf(userScore));
        variableComputerScore.setText(String.valueOf(computerScore));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        scissors1 = new javax.swing.JLabel();
        scissors = new javax.swing.JLabel();
        loseMessage = new javax.swing.JLabel();
        winMessage = new javax.swing.JLabel();
        rock1 = new javax.swing.JLabel();
        paper = new javax.swing.JLabel();
        rock = new javax.swing.JLabel();
        paper1 = new javax.swing.JLabel();
        playAgain = new javax.swing.JLabel();
        yes = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        variableUserScore = new javax.swing.JLabel();
        variableComputerScore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        drawMessage = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        scissors1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/scissors.png"))); // NOI18N
        getContentPane().add(scissors1);
        scissors1.setBounds(830, 0, 230, 210);

        scissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/scissors.png"))); // NOI18N
        scissors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scissorsMouseClicked(evt);
            }
        });
        getContentPane().add(scissors);
        scissors.setBounds(610, 0, 230, 210);

        loseMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/lost_image.png"))); // NOI18N
        getContentPane().add(loseMessage);
        loseMessage.setBounds(320, 230, 530, 350);

        winMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/win_image.jpg"))); // NOI18N
        getContentPane().add(winMessage);
        winMessage.setBounds(350, 240, 440, 330);

        rock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/rock.jpg"))); // NOI18N
        rock1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rock1MouseClicked(evt);
            }
        });
        getContentPane().add(rock1);
        rock1.setBounds(610, 0, 380, 234);

        paper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/paper.png"))); // NOI18N
        paper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paperMouseClicked(evt);
            }
        });
        getContentPane().add(paper);
        paper.setBounds(0, 0, 225, 225);

        rock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/rock.jpg"))); // NOI18N
        rock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rockMouseClicked(evt);
            }
        });
        getContentPane().add(rock);
        rock.setBounds(230, 0, 380, 234);

        paper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/paper.png"))); // NOI18N
        getContentPane().add(paper1);
        paper1.setBounds(220, 0, 225, 225);

        playAgain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/play_again.jpg"))); // NOI18N
        getContentPane().add(playAgain);
        playAgain.setBounds(20, 640, 410, 280);

        yes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/yes_image.png"))); // NOI18N
        yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesMouseClicked(evt);
            }
        });
        getContentPane().add(yes);
        yes.setBounds(450, 650, 310, 260);

        no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/no_icon.png"))); // NOI18N
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMouseClicked(evt);
            }
        });
        getContentPane().add(no);
        no.setBounds(740, 640, 260, 270);

        variableUserScore.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        variableUserScore.setText("(userScore)");
        variableUserScore.setToolTipText("");
        getContentPane().add(variableUserScore);
        variableUserScore.setBounds(1390, 20, 230, 130);

        variableComputerScore.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        variableComputerScore.setText("(computerScore)");
        getContentPane().add(variableComputerScore);
        variableComputerScore.setBounds(1390, 90, 280, 130);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("user score:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1190, 10, 230, 140);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("computer Score:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1100, 120, 300, 70);

        drawMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissorsgui/draw_image.jpg"))); // NOI18N
        drawMessage.setText("jLabel1");
        getContentPane().add(drawMessage);
        drawMessage.setBounds(-50, 270, 1230, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rockMouseClicked
 
        
        int computer = rand.nextInt(3)+1;  
        if (computer  == 1){
            loseMessage.setVisible(true);
            scissors.setVisible(false);
            computerScore++;
        }
        else if(computer == 2){
            drawMessage.setVisible(true);
            scissors.setVisible(false);
            paper.setVisible(false);
            rock1.setVisible(true);
        
        }
        else if (computer == 3){
            winMessage.setVisible(true);           
            paper.setVisible(false);
            userScore++;       
        }
        playAgain.setVisible(true);
        yes.setVisible(true);
        no.setVisible(true);

        
    }//GEN-LAST:event_rockMouseClicked

    private void rock1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rock1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rock1MouseClicked

    private void yesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseClicked
        this.dispose();
        Game game = new Game();
       
        Toolkit tk = Toolkit.getDefaultToolkit(); 
        int xSize = (int)tk.getScreenSize().getWidth();//gets height and width of screen
        int ySize = (int)tk.getScreenSize().getHeight();
        game.setSize(xSize,ySize);//width, height
        game.setVisible(true);
        
    }//GEN-LAST:event_yesMouseClicked

    private void noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseClicked
        this.dispose();
    }//GEN-LAST:event_noMouseClicked

    private void paperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paperMouseClicked
        int computer = rand.nextInt(3)+1;  
        if (computer  == 1){
            loseMessage.setVisible(true);
            rock.setVisible(false);
            computerScore++;
        }
        else if(computer == 2){
            drawMessage.setVisible(true);
            scissors.setVisible(false);
            rock.setVisible(false);
            paper1.setVisible(true);
        
        }
        else if (computer == 3){
            winMessage.setVisible(true);           
            scissors.setVisible(false);
            userScore++;       
        }
        playAgain.setVisible(true);
        yes.setVisible(true);
        no.setVisible(true);
    }//GEN-LAST:event_paperMouseClicked

    private void scissorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scissorsMouseClicked
        int computer = rand.nextInt(3)+1;  
        if (computer  == 1){
            loseMessage.setVisible(true);
            paper.setVisible(false);
            computerScore++;
        }
        else if(computer == 2){
            drawMessage.setVisible(true);
            paper.setVisible(false);
            rock.setVisible(false);
            scissors1.setVisible(true);
        
        }
        else if (computer == 3){
            winMessage.setVisible(true);           
            rock.setVisible(false);
            userScore++;       
        }
        playAgain.setVisible(true);
        yes.setVisible(true);
        no.setVisible(true);
    }//GEN-LAST:event_scissorsMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drawMessage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel loseMessage;
    private javax.swing.JLabel no;
    private javax.swing.JLabel paper;
    private javax.swing.JLabel paper1;
    private javax.swing.JLabel playAgain;
    private javax.swing.JLabel rock;
    private javax.swing.JLabel rock1;
    private javax.swing.JLabel scissors;
    private javax.swing.JLabel scissors1;
    private javax.swing.JLabel variableComputerScore;
    private javax.swing.JLabel variableUserScore;
    private javax.swing.JLabel winMessage;
    private javax.swing.JLabel yes;
    // End of variables declaration//GEN-END:variables
}
